local et = _G.et

local starting_estates = {
    vik_reg_na_seciri = true,
    vik_reg_theodford = true,
    vik_reg_cair_segeint = true,
    vik_reg_oxnaforda = true,
    vik_reg_cenannas = true,
    vik_reg_doneceaster = true,
    vik_reg_bathanceaster = true,
    vik_reg_scireburnan = true,
    vik_reg_staefford = false,
    vik_reg_dun_eachainn = false,
    vik_reg_ethandun = false,
    vik_reg_suthhamtun = false,
    vik_reg_wiht = false,
    vik_reg_waecet = false,
    vik_reg_sceaftesburg = false,
    vik_reg_cissanbyrig = false,
    vik_reg_brug = false,
    vik_reg_ardach = false,
    vik_reg_dear = false,
    vik_reg_rinnin = false,
    vik_reg_celmeresfort = false,
    vik_reg_sancte_albanes = false,
    vik_reg_domuc = false,
    vik_reg_inis_patraic = false,
    vik_reg_eofesham = false,
    vik_reg_glastingburi = false,
    vik_reg_licetfelda = false
} --:map<string, boolean>

ESTATES_EFFECTS = {
	["vik_abbey_1"] = { ["building"] = "vik_abbey_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_abbey_2"] = { ["building"] = "vik_abbey_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_abbey_3"] = { ["building"] = "vik_abbey_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_abbey_4"] = { ["building"] = "vik_abbey_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_abbey_5"] = { ["building"] = "vik_abbey_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_cloth_1"] = { ["building"] = "vik_cloth_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_cloth_2"] = { ["building"] = "vik_cloth_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_cloth_3"] = { ["building"] = "vik_cloth_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_cloth_4"] = { ["building"] = "vik_cloth_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_cloth_5"] = { ["building"] = "vik_cloth_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_cloth_b_4"] = { ["building"] = "vik_cloth_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_cloth_b_5"] = { ["building"] = "vik_cloth_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_copper_1"] = { ["building"] = "vik_copper_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_copper_2"] = { ["building"] = "vik_copper_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_copper_3"] = { ["building"] = "vik_copper_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_copper_4"] = { ["building"] = "vik_copper_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_copper_5"] = { ["building"] = "vik_copper_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_copper_b_4"] = { ["building"] = "vik_copper_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_copper_b_5"] = { ["building"] = "vik_copper_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_1"] = { ["building"] = "vik_farm_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_2"] = { ["building"] = "vik_farm_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_3"] = { ["building"] = "vik_farm_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_4"] = { ["building"] = "vik_farm_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_5"] = { ["building"] = "vik_farm_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_b_4"] = { ["building"] = "vik_farm_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_b_5"] = { ["building"] = "vik_farm_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_fishing_1"] = { ["building"] = "vik_fishing_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_fishing_2"] = { ["building"] = "vik_fishing_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_fishing_3"] = { ["building"] = "vik_fishing_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_fishing_4"] = { ["building"] = "vik_fishing_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_fishing_5"] = { ["building"] = "vik_fishing_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_fishing_b_4"] = { ["building"] = "vik_fishing_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_fishing_b_5"] = { ["building"] = "vik_fishing_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_1"] = { ["building"] = "vik_gold_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_2"] = { ["building"] = "vik_gold_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_3"] = { ["building"] = "vik_gold_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_4"] = { ["building"] = "vik_gold_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_5"] = { ["building"] = "vik_gold_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_b_4"] = { ["building"] = "vik_gold_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_b_5"] = { ["building"] = "vik_gold_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_1"] = { ["building"] = "vik_hunting_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_2"] = { ["building"] = "vik_hunting_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_3"] = { ["building"] = "vik_hunting_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_4"] = { ["building"] = "vik_hunting_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_5"] = { ["building"] = "vik_hunting_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_b_4"] = { ["building"] = "vik_hunting_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_b_5"] = { ["building"] = "vik_hunting_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_iron_1"] = { ["building"] = "vik_iron_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_iron_2"] = { ["building"] = "vik_iron_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_iron_3"] = { ["building"] = "vik_iron_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_iron_4"] = { ["building"] = "vik_iron_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_iron_5"] = { ["building"] = "vik_iron_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_iron_b_4"] = { ["building"] = "vik_iron_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_iron_b_5"] = { ["building"] = "vik_iron_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_lead_1"] = { ["building"] = "vik_lead_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_lead_2"] = { ["building"] = "vik_lead_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_lead_3"] = { ["building"] = "vik_lead_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_lead_4"] = { ["building"] = "vik_lead_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_lead_5"] = { ["building"] = "vik_lead_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_lead_b_4"] = { ["building"] = "vik_lead_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_lead_b_5"] = { ["building"] = "vik_lead_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_1"] = { ["building"] = "vik_orchard_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_2"] = { ["building"] = "vik_orchard_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_3"] = { ["building"] = "vik_orchard_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_4"] = { ["building"] = "vik_orchard_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_5"] = { ["building"] = "vik_orchard_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_b_4"] = { ["building"] = "vik_orchard_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_b_5"] = { ["building"] = "vik_orchard_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_1"] = { ["building"] = "vik_pasture_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_2"] = { ["building"] = "vik_pasture_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_3"] = { ["building"] = "vik_pasture_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_4"] = { ["building"] = "vik_pasture_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_5"] = { ["building"] = "vik_pasture_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_b_4"] = { ["building"] = "vik_pasture_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_b_5"] = { ["building"] = "vik_pasture_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pottery_1"] = { ["building"] = "vik_pottery_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pottery_2"] = { ["building"] = "vik_pottery_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pottery_3"] = { ["building"] = "vik_pottery_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pottery_4"] = { ["building"] = "vik_pottery_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pottery_5"] = { ["building"] = "vik_pottery_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pottery_b_4"] = { ["building"] = "vik_pottery_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pottery_b_5"] = { ["building"] = "vik_pottery_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_salt_1"] = { ["building"] = "vik_salt_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_salt_2"] = { ["building"] = "vik_salt_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_salt_3"] = { ["building"] = "vik_salt_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_salt_4"] = { ["building"] = "vik_salt_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_salt_5"] = { ["building"] = "vik_salt_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_salt_b_4"] = { ["building"] = "vik_salt_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_salt_b_5"] = { ["building"] = "vik_salt_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_1"] = { ["building"] = "vik_silver_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_2"] = { ["building"] = "vik_silver_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_3"] = { ["building"] = "vik_silver_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_4"] = { ["building"] = "vik_silver_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_5"] = { ["building"] = "vik_silver_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_b_4"] = { ["building"] = "vik_silver_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_b_5"] = { ["building"] = "vik_silver_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_tin_1"] = { ["building"] = "vik_tin_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_tin_2"] = { ["building"] = "vik_tin_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_tin_3"] = { ["building"] = "vik_tin_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_tin_4"] = { ["building"] = "vik_tin_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_tin_5"] = { ["building"] = "vik_tin_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_tin_b_4"] = { ["building"] = "vik_tin_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_tin_b_5"] = { ["building"] = "vik_tin_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_trade_1"] = { ["building"] = "vik_trade_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_trade_2"] = { ["building"] = "vik_trade_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_trade_3"] = { ["building"] = "vik_trade_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_trade_4"] = { ["building"] = "vik_trade_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_trade_5"] = { ["building"] = "vik_trade_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_trade_b_4"] = { ["building"] = "vik_trade_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_trade_b_5"] = { ["building"] = "vik_trade_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_wood_1"] = { ["building"] = "vik_wood_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_wood_2"] = { ["building"] = "vik_wood_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_wood_3"] = { ["building"] = "vik_wood_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_wood_4"] = { ["building"] = "vik_wood_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_wood_5"] = { ["building"] = "vik_wood_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_wood_b_4"] = { ["building"] = "vik_wood_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_wood_b_5"] = { ["building"] = "vik_wood_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_b_2"] = { ["building"] = "vik_farm_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_b_3"] = { ["building"] = "vik_farm_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_cloth_b_2"] = { ["building"] = "vik_cloth_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_cloth_b_3"] = { ["building"] = "vik_cloth_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_copper_b_2"] = { ["building"] = "vik_copper_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_copper_b_3"] = { ["building"] = "vik_copper_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_fishing_b_2"] = { ["building"] = "vik_fishing_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_fishing_b_3"] = { ["building"] = "vik_fishing_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_b_2"] = { ["building"] = "vik_gold_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_b_3"] = { ["building"] = "vik_gold_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_b_2"] = { ["building"] = "vik_hunting_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_b_3"] = { ["building"] = "vik_hunting_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_iron_b_2"] = { ["building"] = "vik_iron_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_iron_b_3"] = { ["building"] = "vik_iron_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_lead_b_2"] = { ["building"] = "vik_lead_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_lead_b_3"] = { ["building"] = "vik_lead_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_b_2"] = { ["building"] = "vik_orchard_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_b_3"] = { ["building"] = "vik_orchard_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_b_2"] = { ["building"] = "vik_pasture_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_b_3"] = { ["building"] = "vik_pasture_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pottery_b_2"] = { ["building"] = "vik_pottery_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pottery_b_3"] = { ["building"] = "vik_pottery_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_salt_b_2"] = { ["building"] = "vik_salt_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_salt_b_3"] = { ["building"] = "vik_salt_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_b_2"] = { ["building"] = "vik_silver_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_b_3"] = { ["building"] = "vik_silver_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_tin_b_2"] = { ["building"] = "vik_tin_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_tin_b_3"] = { ["building"] = "vik_tin_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_wood_b_2"] = { ["building"] = "vik_wood_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_wood_b_3"] = { ["building"] = "vik_wood_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_benedictine_abbey_1"] = { ["building"] = "vik_benedictine_abbey_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_benedictine_abbey_2"] = { ["building"] = "vik_benedictine_abbey_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_benedictine_abbey_3"] = { ["building"] = "vik_benedictine_abbey_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_benedictine_abbey_4"] = { ["building"] = "vik_benedictine_abbey_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_benedictine_abbey_5"] = { ["building"] = "vik_benedictine_abbey_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_celi_de_abbey_1"] = { ["building"] = "vik_celi_de_abbey_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_celi_de_abbey_2"] = { ["building"] = "vik_celi_de_abbey_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_celi_de_abbey_3"] = { ["building"] = "vik_celi_de_abbey_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_celi_de_abbey_4"] = { ["building"] = "vik_celi_de_abbey_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_celi_de_abbey_5"] = { ["building"] = "vik_celi_de_abbey_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_school_ros_1"] = { ["building"] = "vik_school_ros_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_school_ros_2"] = { ["building"] = "vik_school_ros_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_school_ros_3"] = { ["building"] = "vik_school_ros_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_school_ros_4"] = { ["building"] = "vik_school_ros_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_school_ros_5"] = { ["building"] = "vik_school_ros_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_cuthbert_1"] = { ["building"] = "vik_st_cuthbert_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_cuthbert_2"] = { ["building"] = "vik_st_cuthbert_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_cuthbert_3"] = { ["building"] = "vik_st_cuthbert_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_cuthbert_4"] = { ["building"] = "vik_st_cuthbert_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_cuthbert_5"] = { ["building"] = "vik_st_cuthbert_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_dewi_1"] = { ["building"] = "vik_st_dewi_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_dewi_2"] = { ["building"] = "vik_st_dewi_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_dewi_3"] = { ["building"] = "vik_st_dewi_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_dewi_4"] = { ["building"] = "vik_st_dewi_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_dewi_5"] = { ["building"] = "vik_st_dewi_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_edmund_1"] = { ["building"] = "vik_st_edmund_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_edmund_2"] = { ["building"] = "vik_st_edmund_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_edmund_3"] = { ["building"] = "vik_st_edmund_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_edmund_4"] = { ["building"] = "vik_st_edmund_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_edmund_5"] = { ["building"] = "vik_st_edmund_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ringan_1"] = { ["building"] = "vik_st_ringan_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ringan_2"] = { ["building"] = "vik_st_ringan_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ringan_3"] = { ["building"] = "vik_st_ringan_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ringan_4"] = { ["building"] = "vik_st_ringan_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ringan_5"] = { ["building"] = "vik_st_ringan_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_achad_bo_1"] = { ["building"] = "vik_achad_bo_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_achad_bo_2"] = { ["building"] = "vik_achad_bo_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_achad_bo_3"] = { ["building"] = "vik_achad_bo_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_achad_bo_4"] = { ["building"] = "vik_achad_bo_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_achad_bo_5"] = { ["building"] = "vik_achad_bo_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_great_hall_1"] = { ["building"] = "vik_great_hall_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_great_hall_2"] = { ["building"] = "vik_great_hall_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_great_hall_3"] = { ["building"] = "vik_great_hall_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_great_hall_4"] = { ["building"] = "vik_great_hall_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_great_hall_5"] = { ["building"] = "vik_great_hall_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_grianan_ailech_1"] = { ["building"] = "vik_grianan_ailech_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_grianan_ailech_2"] = { ["building"] = "vik_grianan_ailech_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_grianan_ailech_3"] = { ["building"] = "vik_grianan_ailech_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_grianan_ailech_4"] = { ["building"] = "vik_grianan_ailech_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_grianan_ailech_5"] = { ["building"] = "vik_grianan_ailech_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_longphort_1"] = { ["building"] = "vik_longphort_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_longphort_2"] = { ["building"] = "vik_longphort_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_longphort_3"] = { ["building"] = "vik_longphort_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_longphort_4"] = { ["building"] = "vik_longphort_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_longphort_5"] = { ["building"] = "vik_longphort_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_market_1"] = { ["building"] = "vik_market_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_market_2"] = { ["building"] = "vik_market_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_market_3"] = { ["building"] = "vik_market_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_market_4"] = { ["building"] = "vik_market_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_market_5"] = { ["building"] = "vik_market_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_monastery_1"] = { ["building"] = "vik_monastery_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_monastery_2"] = { ["building"] = "vik_monastery_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_monastery_3"] = { ["building"] = "vik_monastery_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_monastery_4"] = { ["building"] = "vik_monastery_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_monastery_5"] = { ["building"] = "vik_monastery_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_mountain_hall_1"] = { ["building"] = "vik_mountain_hall_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_mountain_hall_2"] = { ["building"] = "vik_mountain_hall_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_mountain_hall_3"] = { ["building"] = "vik_mountain_hall_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_mountain_hall_4"] = { ["building"] = "vik_mountain_hall_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_mountain_hall_5"] = { ["building"] = "vik_mountain_hall_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_offas_hall_1"] = { ["building"] = "vik_offas_hall_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_offas_hall_2"] = { ["building"] = "vik_offas_hall_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_offas_hall_3"] = { ["building"] = "vik_offas_hall_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_offas_hall_4"] = { ["building"] = "vik_offas_hall_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_offas_hall_5"] = { ["building"] = "vik_offas_hall_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_rock_caisil_1"] = { ["building"] = "vik_rock_caisil_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_rock_caisil_2"] = { ["building"] = "vik_rock_caisil_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_rock_caisil_3"] = { ["building"] = "vik_rock_caisil_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_rock_caisil_4"] = { ["building"] = "vik_rock_caisil_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_rock_caisil_5"] = { ["building"] = "vik_rock_caisil_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ciaran_1"] = { ["building"] = "vik_st_ciaran_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ciaran_2"] = { ["building"] = "vik_st_ciaran_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ciaran_3"] = { ["building"] = "vik_st_ciaran_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ciaran_4"] = { ["building"] = "vik_st_ciaran_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ciaran_5"] = { ["building"] = "vik_st_ciaran_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_columbe_1"] = { ["building"] = "vik_st_columbe_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_columbe_2"] = { ["building"] = "vik_st_columbe_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_columbe_3"] = { ["building"] = "vik_st_columbe_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_columbe_4"] = { ["building"] = "vik_st_columbe_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_columbe_5"] = { ["building"] = "vik_st_columbe_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_patraic_1"] = { ["building"] = "vik_st_patraic_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_patraic_2"] = { ["building"] = "vik_st_patraic_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_patraic_3"] = { ["building"] = "vik_st_patraic_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_patraic_4"] = { ["building"] = "vik_st_patraic_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_patraic_5"] = { ["building"] = "vik_st_patraic_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 }
} --:map<string, {building: string, effect: string, effect_scope: string, value: number, value_damaged: number, value_ruined: number}>

for building, row in pairs(ESTATES_EFFECTS) do
    et:add_estate_to_building(building, row.effect)
end



cm:register_first_tick_callback( function()
    if cm:is_new_game() then
        for key, value in pairs(starting_estates) do
            et:create_start_pos_estate(key, value)
        end
    end
end)

