local start_pos_estates = {
    --wessex
    {"vik_reg_werham", "2147363513", "vik_market_1", "vik_fact_west_seaxe"},
    {"vik_reg_aethelingaeg", "2147363108", "vik_great_hall_1", "vik_fact_west_seaxe"},
    {"vik_reg_cippanhamm", "2147363267", "vik_great_hall_1", "vik_fact_west_seaxe"},
    {"vik_reg_doreceaster", "2147363612", "vik_great_hall_1", "vik_fact_west_seaxe"},
    --mierce
    {"vik_reg_ceaster", "2147363335", "vik_market_1", "vik_fact_mierce"},
    {"vik_reg_ceaster", "2147363481", "vik_estate_1", "vik_fact_mierce"},
    {"vik_reg_waerincwicum", "2147363475", "vik_great_hall_1", "vik_fact_mierce"},
    {"vik_reg_cirenceaster", "2147363540", "vik_silver_1", "vik_fact_mierce"},
    --strat clut
    {"vik_reg_sreth_belin", "2147367306", "vik_silver_1", "vik_fact_strat_clut"},
    --mide
    {"vik_reg_ardach", "2147365091", "vik_silver_1", "vik_fact_mide"},
    --circenn
    {"vik_reg_ardach", "2147364675", "vik_great_hall_1", "vik_fact_circenn"},
    --east angle
    {"vik_reg_lunden", "2147366738", "vik_market_2", "vik_fact_east_engle"},
    {"vik_reg_colneceaster", "2147366862", "vik_great_hall_1", "vik_fact_east_engle"},
    {"vik_reg_rendlesham", "2147366741", "vik_great_hall_1", "vik_fact_east_engle"},
    --northymbre
    {"vik_reg_loidis", "2147367004", "vik_market_1", "vik_fact_northymbre"},
    {"vik_reg_cetretha", "2147366934", "vik_great_hall_1", "vik_fact_northymbre"},
    {"vik_reg_mameceaster", "2147366741", "vik_great_hall_1", "vik_fact_northymbre"},
    {"vik_reg_dunholm", "2147366761", "vik_st_cuthbert_1", "vik_fact_northymbre"},
    --dyflin
    {"vik_reg_casteltoun", "2147366227", "vik_longphort_1", "vik_fact_dyflin"},
    --sudreyar
    {"vik_reg_ioua", "2147365995", "vik_monastery_1", "vik_fact_sudreyar"},
    {"vik_reg_dun_beccan", "2147366135", "vik_silver_1", "vik_fact_sudreyar"},
} --:vector<{string, string, string, string}>


local cd = _G.cd;

for i = 1, #start_pos_estates do
    local name = "names_name_" .. start_pos_estates[i][2] 
    local region = start_pos_estates[i][1]
    local building = start_pos_estates[i][3]
    local faction = start_pos_estates[i][4]
    cd.register_startpos_estate(region, name, building, faction)
end


local building_estate_effects = {
	["vik_achad_bo_1"] = { ["building"] = "vik_achad_bo_1", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_achad_bo_2"] = { ["building"] = "vik_achad_bo_2", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_achad_bo_3"] = { ["building"] = "vik_achad_bo_3", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_achad_bo_4"] = { ["building"] = "vik_achad_bo_4", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_achad_bo_5"] = { ["building"] = "vik_achad_bo_5", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ciaran_1"] = { ["building"] = "vik_st_ciaran_1", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ciaran_2"] = { ["building"] = "vik_st_ciaran_2", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ciaran_3"] = { ["building"] = "vik_st_ciaran_3", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ciaran_4"] = { ["building"] = "vik_st_ciaran_4", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ciaran_5"] = { ["building"] = "vik_st_ciaran_5", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_columbe_1"] = { ["building"] = "vik_st_columbe_1", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_columbe_2"] = { ["building"] = "vik_st_columbe_2", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_columbe_3"] = { ["building"] = "vik_st_columbe_3", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_columbe_4"] = { ["building"] = "vik_st_columbe_4", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_columbe_5"] = { ["building"] = "vik_st_columbe_5", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_patraic_1"] = { ["building"] = "vik_st_patraic_1", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_patraic_2"] = { ["building"] = "vik_st_patraic_2", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_patraic_3"] = { ["building"] = "vik_st_patraic_3", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_patraic_4"] = { ["building"] = "vik_st_patraic_4", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_patraic_5"] = { ["building"] = "vik_st_patraic_5", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_mountain_hall_1"] = { ["building"] = "vik_mountain_hall_1", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_mountain_hall_2"] = { ["building"] = "vik_mountain_hall_2", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_mountain_hall_3"] = { ["building"] = "vik_mountain_hall_3", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_mountain_hall_4"] = { ["building"] = "vik_mountain_hall_4", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_mountain_hall_5"] = { ["building"] = "vik_mountain_hall_5", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_monastery_1"] = { ["building"] = "vik_monastery_1", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_monastery_2"] = { ["building"] = "vik_monastery_2", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_monastery_3"] = { ["building"] = "vik_monastery_3", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_monastery_4"] = { ["building"] = "vik_monastery_4", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_monastery_5"] = { ["building"] = "vik_monastery_5", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_grianan_ailech_1"] = { ["building"] = "vik_grianan_ailech_1", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_grianan_ailech_2"] = { ["building"] = "vik_grianan_ailech_2", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_grianan_ailech_3"] = { ["building"] = "vik_grianan_ailech_3", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_grianan_ailech_4"] = { ["building"] = "vik_grianan_ailech_4", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_grianan_ailech_5"] = { ["building"] = "vik_grianan_ailech_5", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_great_hall_1"] = { ["building"] = "vik_great_hall_1", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_great_hall_2"] = { ["building"] = "vik_great_hall_2", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_great_hall_3"] = { ["building"] = "vik_great_hall_3", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_great_hall_4"] = { ["building"] = "vik_great_hall_4", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_great_hall_5"] = { ["building"] = "vik_great_hall_5", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_longphort_1"] = { ["building"] = "vik_longphort_1", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_longphort_2"] = { ["building"] = "vik_longphort_2", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_longphort_3"] = { ["building"] = "vik_longphort_3", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_longphort_4"] = { ["building"] = "vik_longphort_4", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_longphort_5"] = { ["building"] = "vik_longphort_5", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_market_1"] = { ["building"] = "vik_market_1", ["effect"] = "shield_estates_commerce", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_market_2"] = { ["building"] = "vik_market_2", ["effect"] = "shield_estates_commerce", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_market_3"] = { ["building"] = "vik_market_3", ["effect"] = "shield_estates_commerce", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_market_4"] = { ["building"] = "vik_market_4", ["effect"] = "shield_estates_commerce", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_market_5"] = { ["building"] = "vik_market_5", ["effect"] = "shield_estates_commerce", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_offas_hall_1"] = { ["building"] = "vik_offas_hall_1", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_offas_hall_2"] = { ["building"] = "vik_offas_hall_2", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_offas_hall_3"] = { ["building"] = "vik_offas_hall_3", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_offas_hall_4"] = { ["building"] = "vik_offas_hall_4", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_offas_hall_5"] = { ["building"] = "vik_offas_hall_5", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_rock_caisil_1"] = { ["building"] = "vik_rock_caisil_1", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_rock_caisil_2"] = { ["building"] = "vik_rock_caisil_2", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_rock_caisil_3"] = { ["building"] = "vik_rock_caisil_3", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_rock_caisil_4"] = { ["building"] = "vik_rock_caisil_4", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_rock_caisil_5"] = { ["building"] = "vik_rock_caisil_5", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ringan_1"] = { ["building"] = "vik_st_ringan_1", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ringan_2"] = { ["building"] = "vik_st_ringan_2", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ringan_3"] = { ["building"] = "vik_st_ringan_3", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ringan_4"] = { ["building"] = "vik_st_ringan_4", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ringan_5"] = { ["building"] = "vik_st_ringan_5", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_cuthbert_1"] = { ["building"] = "vik_st_cuthbert_1", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_cuthbert_2"] = { ["building"] = "vik_st_cuthbert_2", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_cuthbert_3"] = { ["building"] = "vik_st_cuthbert_3", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_cuthbert_4"] = { ["building"] = "vik_st_cuthbert_4", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_cuthbert_5"] = { ["building"] = "vik_st_cuthbert_5", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_dewi_1"] = { ["building"] = "vik_st_dewi_1", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_dewi_2"] = { ["building"] = "vik_st_dewi_2", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_dewi_3"] = { ["building"] = "vik_st_dewi_3", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_dewi_4"] = { ["building"] = "vik_st_dewi_4", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_dewi_5"] = { ["building"] = "vik_st_dewi_5", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_edmund_1"] = { ["building"] = "vik_st_edmund_1", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_edmund_2"] = { ["building"] = "vik_st_edmund_2", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_edmund_3"] = { ["building"] = "vik_st_edmund_3", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_edmund_4"] = { ["building"] = "vik_st_edmund_4", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_edmund_5"] = { ["building"] = "vik_st_edmund_5", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_school_ros_1"] = { ["building"] = "vik_school_ros_1", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_school_ros_2"] = { ["building"] = "vik_school_ros_2", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_school_ros_3"] = { ["building"] = "vik_school_ros_3", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_school_ros_4"] = { ["building"] = "vik_school_ros_4", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_school_ros_5"] = { ["building"] = "vik_school_ros_5", ["effect"] = "shield_estates_church", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_tin_3"] = { ["building"] = "vik_tin_3", ["effect"] = "shield_estates_commerce", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_1"] = { ["building"] = "vik_silver_1", ["effect"] = "shield_estates_commerce", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_2"] = { ["building"] = "vik_silver_2", ["effect"] = "shield_estates_commerce", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_3"] = { ["building"] = "vik_silver_3", ["effect"] = "shield_estates_commerce", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_b_3"] = { ["building"] = "vik_silver_b_3", ["effect"] = "shield_estates_commerce", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_iron_3"] = { ["building"] = "vik_iron_3", ["effect"] = "shield_estates_commerce", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_1"] = { ["building"] = "vik_gold_1", ["effect"] = "shield_estates_commerce", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_2"] = { ["building"] = "vik_gold_2", ["effect"] = "shield_estates_commerce", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_3"] = { ["building"] = "vik_gold_3", ["effect"] = "shield_estates_commerce", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_b_3"] = { ["building"] = "vik_gold_b_3", ["effect"] = "shield_estates_commerce", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_copper_3"] = { ["building"] = "vik_copper_3", ["effect"] = "shield_estates_commerce", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_b_2"] = { ["building"] = "vik_farm_b_2", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_b_3"] = { ["building"] = "vik_farm_b_3", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_b_4"] = { ["building"] = "vik_farm_b_4", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_b_5"] = { ["building"] = "vik_farm_b_5", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_b_2"] = { ["building"] = "vik_hunting_b_2", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_b_3"] = { ["building"] = "vik_hunting_b_3", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_b_4"] = { ["building"] = "vik_hunting_b_4", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_b_5"] = { ["building"] = "vik_hunting_b_5", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_b_2"] = { ["building"] = "vik_orchard_b_2", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_b_3"] = { ["building"] = "vik_orchard_b_3", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_b_4"] = { ["building"] = "vik_orchard_b_4", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_b_5"] = { ["building"] = "vik_orchard_b_5", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_b_2"] = { ["building"] = "vik_pasture_b_2", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_b_3"] = { ["building"] = "vik_pasture_b_3", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_b_4"] = { ["building"] = "vik_pasture_b_4", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_b_5"] = { ["building"] = "vik_pasture_b_5", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_garrison_2"] = { ["building"] = "vik_garrison_2", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_estate_1"] = { ["building"] = "vik_estate_1", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_estate_2"] = { ["building"] = "vik_estate_2", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_estate_3"] = { ["building"] = "vik_estate_3", ["effect"] = "shield_estates_landed", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 }
} --:map<string, {building: string, effect: string, effect_scope: string, value: number, value_damaged: number, value_ruined:number}>

local estate_household_growths = {
	["vik_achad_bo_1"] = { ["building"] = "vik_achad_bo_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 3, ["value_damaged"] = 3, ["value_ruined"] = 0 },
	["vik_achad_bo_2"] = { ["building"] = "vik_achad_bo_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 5, ["value_damaged"] = 5, ["value_ruined"] = 0 },
	["vik_achad_bo_3"] = { ["building"] = "vik_achad_bo_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 7, ["value_damaged"] = 7, ["value_ruined"] = 0 },
	["vik_achad_bo_4"] = { ["building"] = "vik_achad_bo_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 9, ["value_damaged"] = 9, ["value_ruined"] = 0 },
	["vik_achad_bo_5"] = { ["building"] = "vik_achad_bo_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 12, ["value_damaged"] = 12, ["value_ruined"] = 0 },
	["vik_st_ciaran_1"] = { ["building"] = "vik_st_ciaran_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 3, ["value_damaged"] = 3, ["value_ruined"] = 0 },
	["vik_st_ciaran_2"] = { ["building"] = "vik_st_ciaran_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 5, ["value_damaged"] = 5, ["value_ruined"] = 0 },
	["vik_st_ciaran_3"] = { ["building"] = "vik_st_ciaran_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 7, ["value_damaged"] = 7, ["value_ruined"] = 0 },
	["vik_st_ciaran_4"] = { ["building"] = "vik_st_ciaran_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 9, ["value_damaged"] = 9, ["value_ruined"] = 0 },
	["vik_st_ciaran_5"] = { ["building"] = "vik_st_ciaran_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 12, ["value_damaged"] = 12, ["value_ruined"] = 0 },
	["vik_st_columbe_1"] = { ["building"] = "vik_st_columbe_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 3, ["value_damaged"] = 3, ["value_ruined"] = 0 },
	["vik_st_columbe_2"] = { ["building"] = "vik_st_columbe_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 5, ["value_damaged"] = 5, ["value_ruined"] = 0 },
	["vik_st_columbe_3"] = { ["building"] = "vik_st_columbe_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 7, ["value_damaged"] = 7, ["value_ruined"] = 0 },
	["vik_st_columbe_4"] = { ["building"] = "vik_st_columbe_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 9, ["value_damaged"] = 9, ["value_ruined"] = 0 },
	["vik_st_columbe_5"] = { ["building"] = "vik_st_columbe_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 12, ["value_damaged"] = 12, ["value_ruined"] = 0 },
	["vik_st_patraic_1"] = { ["building"] = "vik_st_patraic_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 3, ["value_damaged"] = 3, ["value_ruined"] = 0 },
	["vik_st_patraic_2"] = { ["building"] = "vik_st_patraic_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 5, ["value_damaged"] = 5, ["value_ruined"] = 0 },
	["vik_st_patraic_3"] = { ["building"] = "vik_st_patraic_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 7, ["value_damaged"] = 7, ["value_ruined"] = 0 },
	["vik_st_patraic_4"] = { ["building"] = "vik_st_patraic_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 9, ["value_damaged"] = 9, ["value_ruined"] = 0 },
	["vik_st_patraic_5"] = { ["building"] = "vik_st_patraic_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 12, ["value_damaged"] = 12, ["value_ruined"] = 0 },
	["vik_mountain_hall_1"] = { ["building"] = "vik_mountain_hall_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 3, ["value_damaged"] = 3, ["value_ruined"] = 0 },
	["vik_mountain_hall_2"] = { ["building"] = "vik_mountain_hall_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 5, ["value_damaged"] = 5, ["value_ruined"] = 0 },
	["vik_mountain_hall_3"] = { ["building"] = "vik_mountain_hall_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 7, ["value_damaged"] = 7, ["value_ruined"] = 0 },
	["vik_mountain_hall_4"] = { ["building"] = "vik_mountain_hall_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 9, ["value_damaged"] = 9, ["value_ruined"] = 0 },
	["vik_mountain_hall_5"] = { ["building"] = "vik_mountain_hall_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 12, ["value_damaged"] = 12, ["value_ruined"] = 0 },
	["vik_monastery_1"] = { ["building"] = "vik_monastery_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 2, ["value_damaged"] = 2, ["value_ruined"] = 0 },
	["vik_monastery_2"] = { ["building"] = "vik_monastery_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 4, ["value_damaged"] = 4, ["value_ruined"] = 0 },
	["vik_monastery_3"] = { ["building"] = "vik_monastery_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 6, ["value_damaged"] = 6, ["value_ruined"] = 0 },
	["vik_monastery_4"] = { ["building"] = "vik_monastery_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 8, ["value_damaged"] = 8, ["value_ruined"] = 0 },
	["vik_monastery_5"] = { ["building"] = "vik_monastery_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 10, ["value_damaged"] = 10, ["value_ruined"] = 0 },
	["vik_grianan_ailech_1"] = { ["building"] = "vik_grianan_ailech_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 3, ["value_damaged"] = 3, ["value_ruined"] = 0 },
	["vik_grianan_ailech_2"] = { ["building"] = "vik_grianan_ailech_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 5, ["value_damaged"] = 5, ["value_ruined"] = 0 },
	["vik_grianan_ailech_3"] = { ["building"] = "vik_grianan_ailech_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 7, ["value_damaged"] = 7, ["value_ruined"] = 0 },
	["vik_grianan_ailech_4"] = { ["building"] = "vik_grianan_ailech_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 9, ["value_damaged"] = 9, ["value_ruined"] = 0 },
	["vik_grianan_ailech_5"] = { ["building"] = "vik_grianan_ailech_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 12, ["value_damaged"] = 12, ["value_ruined"] = 0 },
	["vik_great_hall_1"] = { ["building"] = "vik_great_hall_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 2, ["value_damaged"] = 2, ["value_ruined"] = 0 },
	["vik_great_hall_2"] = { ["building"] = "vik_great_hall_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 4, ["value_damaged"] = 4, ["value_ruined"] = 0 },
	["vik_great_hall_3"] = { ["building"] = "vik_great_hall_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 6, ["value_damaged"] = 6, ["value_ruined"] = 0 },
	["vik_great_hall_4"] = { ["building"] = "vik_great_hall_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 8, ["value_damaged"] = 8, ["value_ruined"] = 0 },
	["vik_great_hall_5"] = { ["building"] = "vik_great_hall_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 10, ["value_damaged"] = 10, ["value_ruined"] = 0 },
	["vik_longphort_1"] = { ["building"] = "vik_longphort_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 2, ["value_damaged"] = 2, ["value_ruined"] = 0 },
	["vik_longphort_2"] = { ["building"] = "vik_longphort_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 4, ["value_damaged"] = 4, ["value_ruined"] = 0 },
	["vik_longphort_3"] = { ["building"] = "vik_longphort_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 6, ["value_damaged"] = 6, ["value_ruined"] = 0 },
	["vik_longphort_4"] = { ["building"] = "vik_longphort_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 8, ["value_damaged"] = 8, ["value_ruined"] = 0 },
	["vik_longphort_5"] = { ["building"] = "vik_longphort_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 10, ["value_damaged"] = 10, ["value_ruined"] = 0 },
	["vik_market_1"] = { ["building"] = "vik_market_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 2, ["value_damaged"] = 2, ["value_ruined"] = 0 },
	["vik_market_2"] = { ["building"] = "vik_market_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 4, ["value_damaged"] = 4, ["value_ruined"] = 0 },
	["vik_market_3"] = { ["building"] = "vik_market_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 6, ["value_damaged"] = 6, ["value_ruined"] = 0 },
	["vik_market_4"] = { ["building"] = "vik_market_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 8, ["value_damaged"] = 8, ["value_ruined"] = 0 },
	["vik_market_5"] = { ["building"] = "vik_market_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 10, ["value_damaged"] = 10, ["value_ruined"] = 0 },
	["vik_offas_hall_1"] = { ["building"] = "vik_offas_hall_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 3, ["value_damaged"] = 3, ["value_ruined"] = 0 },
	["vik_offas_hall_2"] = { ["building"] = "vik_offas_hall_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 5, ["value_damaged"] = 5, ["value_ruined"] = 0 },
	["vik_offas_hall_3"] = { ["building"] = "vik_offas_hall_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 7, ["value_damaged"] = 7, ["value_ruined"] = 0 },
	["vik_offas_hall_4"] = { ["building"] = "vik_offas_hall_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 9, ["value_damaged"] = 9, ["value_ruined"] = 0 },
	["vik_offas_hall_5"] = { ["building"] = "vik_offas_hall_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 12, ["value_damaged"] = 12, ["value_ruined"] = 0 },
	["vik_rock_caisil_1"] = { ["building"] = "vik_rock_caisil_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 3, ["value_damaged"] = 3, ["value_ruined"] = 0 },
	["vik_rock_caisil_2"] = { ["building"] = "vik_rock_caisil_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 5, ["value_damaged"] = 5, ["value_ruined"] = 0 },
	["vik_rock_caisil_3"] = { ["building"] = "vik_rock_caisil_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 7, ["value_damaged"] = 7, ["value_ruined"] = 0 },
	["vik_rock_caisil_4"] = { ["building"] = "vik_rock_caisil_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 9, ["value_damaged"] = 9, ["value_ruined"] = 0 },
	["vik_rock_caisil_5"] = { ["building"] = "vik_rock_caisil_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 12, ["value_damaged"] = 12, ["value_ruined"] = 0 },
	["vik_st_ringan_1"] = { ["building"] = "vik_st_ringan_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 2, ["value_damaged"] = 2, ["value_ruined"] = 0 },
	["vik_st_ringan_2"] = { ["building"] = "vik_st_ringan_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 4, ["value_damaged"] = 4, ["value_ruined"] = 0 },
	["vik_st_ringan_3"] = { ["building"] = "vik_st_ringan_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 6, ["value_damaged"] = 6, ["value_ruined"] = 0 },
	["vik_st_ringan_4"] = { ["building"] = "vik_st_ringan_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 8, ["value_damaged"] = 8, ["value_ruined"] = 0 },
	["vik_st_ringan_5"] = { ["building"] = "vik_st_ringan_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 10, ["value_damaged"] = 10, ["value_ruined"] = 0 },
	["vik_st_cuthbert_1"] = { ["building"] = "vik_st_cuthbert_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 2, ["value_damaged"] = 2, ["value_ruined"] = 0 },
	["vik_st_cuthbert_2"] = { ["building"] = "vik_st_cuthbert_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 4, ["value_damaged"] = 4, ["value_ruined"] = 0 },
	["vik_st_cuthbert_3"] = { ["building"] = "vik_st_cuthbert_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 6, ["value_damaged"] = 6, ["value_ruined"] = 0 },
	["vik_st_cuthbert_4"] = { ["building"] = "vik_st_cuthbert_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 8, ["value_damaged"] = 8, ["value_ruined"] = 0 },
	["vik_st_cuthbert_5"] = { ["building"] = "vik_st_cuthbert_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 10, ["value_damaged"] = 10, ["value_ruined"] = 0 },
	["vik_st_dewi_1"] = { ["building"] = "vik_st_dewi_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 2, ["value_damaged"] = 2, ["value_ruined"] = 0 },
	["vik_st_dewi_2"] = { ["building"] = "vik_st_dewi_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 4, ["value_damaged"] = 4, ["value_ruined"] = 0 },
	["vik_st_dewi_3"] = { ["building"] = "vik_st_dewi_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 6, ["value_damaged"] = 6, ["value_ruined"] = 0 },
	["vik_st_dewi_4"] = { ["building"] = "vik_st_dewi_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 8, ["value_damaged"] = 8, ["value_ruined"] = 0 },
	["vik_st_dewi_5"] = { ["building"] = "vik_st_dewi_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 10, ["value_damaged"] = 10, ["value_ruined"] = 0 },
	["vik_st_edmund_1"] = { ["building"] = "vik_st_edmund_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 2, ["value_damaged"] = 2, ["value_ruined"] = 0 },
	["vik_st_edmund_2"] = { ["building"] = "vik_st_edmund_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 4, ["value_damaged"] = 4, ["value_ruined"] = 0 },
	["vik_st_edmund_3"] = { ["building"] = "vik_st_edmund_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 6, ["value_damaged"] = 6, ["value_ruined"] = 0 },
	["vik_st_edmund_4"] = { ["building"] = "vik_st_edmund_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 8, ["value_damaged"] = 8, ["value_ruined"] = 0 },
	["vik_st_edmund_5"] = { ["building"] = "vik_st_edmund_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 10, ["value_damaged"] = 10, ["value_ruined"] = 0 },
	["vik_school_ros_1"] = { ["building"] = "vik_school_ros_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 2, ["value_damaged"] = 2, ["value_ruined"] = 0 },
	["vik_school_ros_2"] = { ["building"] = "vik_school_ros_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 4, ["value_damaged"] = 4, ["value_ruined"] = 0 },
	["vik_school_ros_3"] = { ["building"] = "vik_school_ros_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 6, ["value_damaged"] = 6, ["value_ruined"] = 0 },
	["vik_school_ros_4"] = { ["building"] = "vik_school_ros_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 8, ["value_damaged"] = 8, ["value_ruined"] = 0 },
	["vik_school_ros_5"] = { ["building"] = "vik_school_ros_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 10, ["value_damaged"] = 10, ["value_ruined"] = 0 },
	["vik_tin_3"] = { ["building"] = "vik_tin_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 3, ["value_damaged"] = 3, ["value_ruined"] = 0 },
	["vik_silver_1"] = { ["building"] = "vik_silver_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 3, ["value_damaged"] = 3, ["value_ruined"] = 0 },
	["vik_silver_2"] = { ["building"] = "vik_silver_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 6, ["value_damaged"] = 6, ["value_ruined"] = 0 },
	["vik_silver_3"] = { ["building"] = "vik_silver_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 9, ["value_damaged"] = 9, ["value_ruined"] = 0 },
	["vik_silver_b_3"] = { ["building"] = "vik_silver_b_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 9, ["value_damaged"] = 9, ["value_ruined"] = 0 },
	["vik_iron_3"] = { ["building"] = "vik_iron_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 3, ["value_damaged"] = 3, ["value_ruined"] = 0 },
	["vik_gold_1"] = { ["building"] = "vik_gold_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 5, ["value_damaged"] = 5, ["value_ruined"] = 0 },
	["vik_gold_2"] = { ["building"] = "vik_gold_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 10, ["value_damaged"] = 10, ["value_ruined"] = 0 },
	["vik_gold_3"] = { ["building"] = "vik_gold_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 15, ["value_damaged"] = 15, ["value_ruined"] = 0 },
	["vik_gold_b_3"] = { ["building"] = "vik_gold_b_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 15, ["value_damaged"] = 15, ["value_ruined"] = 0 },
	["vik_copper_3"] = { ["building"] = "vik_copper_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 3, ["value_damaged"] = 3, ["value_ruined"] = 0 },
	["vik_farm_b_2"] = { ["building"] = "vik_farm_b_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_b_3"] = { ["building"] = "vik_farm_b_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 2, ["value_damaged"] = 2, ["value_ruined"] = 0 },
	["vik_farm_b_4"] = { ["building"] = "vik_farm_b_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 5, ["value_damaged"] = 5, ["value_ruined"] = 0 },
	["vik_farm_b_5"] = { ["building"] = "vik_farm_b_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 6, ["value_damaged"] = 6, ["value_ruined"] = 0 },
	["vik_hunting_b_2"] = { ["building"] = "vik_hunting_b_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_b_3"] = { ["building"] = "vik_hunting_b_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 2, ["value_damaged"] = 2, ["value_ruined"] = 0 },
	["vik_hunting_b_4"] = { ["building"] = "vik_hunting_b_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 3, ["value_damaged"] = 3, ["value_ruined"] = 0 },
	["vik_hunting_b_5"] = { ["building"] = "vik_hunting_b_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 4, ["value_damaged"] = 4, ["value_ruined"] = 0 },
	["vik_orchard_b_2"] = { ["building"] = "vik_orchard_b_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_b_3"] = { ["building"] = "vik_orchard_b_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 3, ["value_damaged"] = 3, ["value_ruined"] = 0 },
	["vik_orchard_b_4"] = { ["building"] = "vik_orchard_b_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 5, ["value_damaged"] = 5, ["value_ruined"] = 0 },
	["vik_orchard_b_5"] = { ["building"] = "vik_orchard_b_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 7, ["value_damaged"] = 7, ["value_ruined"] = 0 },
	["vik_pasture_b_2"] = { ["building"] = "vik_pasture_b_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 3, ["value_damaged"] = 3, ["value_ruined"] = 0 },
	["vik_pasture_b_3"] = { ["building"] = "vik_pasture_b_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 4, ["value_damaged"] = 4, ["value_ruined"] = 0 },
	["vik_pasture_b_4"] = { ["building"] = "vik_pasture_b_4", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 5, ["value_damaged"] = 5, ["value_ruined"] = 0 },
	["vik_pasture_b_5"] = { ["building"] = "vik_pasture_b_5", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 7, ["value_damaged"] = 7, ["value_ruined"] = 0 },
	["vik_garrison_2"] = { ["building"] = "vik_garrison_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 3, ["value_damaged"] = 3, ["value_ruined"] = 0 },
	["vik_estate_1"] = { ["building"] = "vik_estate_1", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 2, ["value_damaged"] = 2, ["value_ruined"] = 0 },
	["vik_estate_2"] = { ["building"] = "vik_estate_2", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 4, ["value_damaged"] = 4, ["value_ruined"] = 0 },
	["vik_estate_3"] = { ["building"] = "vik_estate_3", ["effect"] = "shield_scripted_household_growth", ["effect_scope"] = "building_to_building_own", ["value"] = 6, ["value_damaged"] = 6, ["value_ruined"] = 0 }
} --:map<string, {building: string, effect: string, effect_scope: string, value: number, value_damaged: number, value_ruined:number}>

local estate_effect_bv = {
    ["shield_estates_landed"] = "vik_estate_agricultural",
    ["shield_estates_commerce"] = "vik_estate_estate_building",
    ["shield_estates_church"] = "vik_estate_religious" 
}--:map<string, string>

local ed = _G.ed
local done_chains = {} --:map<string, boolean>
for building_key, effect_table in pairs(building_estate_effects) do
    local level = building_key
    local chain = level:gsub("[_]?[b]?_%d", "") --ty life advice cabbage
    if (not done_chains[chain]) and estate_effect_bv[effect_table.effect] then
        done_chains[chain] = true
        ed.add_estate_chain_type(chain, estate_effect_bv[effect_table.effect])
    end
    if estate_household_growths[building_key] then
        ed.add_estate_building_level(level, chain, "shieldwall_exp_"..level,  estate_household_growths[building_key].value)
    end
end