local et = _G.et

ESTATES_EFFECTS = {
	["vik_abbey_1"] = { ["building"] = "vik_abbey_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_abbey_2"] = { ["building"] = "vik_abbey_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_abbey_3"] = { ["building"] = "vik_abbey_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_abbey_4"] = { ["building"] = "vik_abbey_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_abbey_5"] = { ["building"] = "vik_abbey_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_cloth_1"] = { ["building"] = "vik_cloth_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_cloth_2"] = { ["building"] = "vik_cloth_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_cloth_3"] = { ["building"] = "vik_cloth_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_cloth_4"] = { ["building"] = "vik_cloth_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_cloth_5"] = { ["building"] = "vik_cloth_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_cloth_b_4"] = { ["building"] = "vik_cloth_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_cloth_b_5"] = { ["building"] = "vik_cloth_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_copper_1"] = { ["building"] = "vik_copper_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_copper_2"] = { ["building"] = "vik_copper_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_copper_3"] = { ["building"] = "vik_copper_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_copper_4"] = { ["building"] = "vik_copper_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_copper_5"] = { ["building"] = "vik_copper_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_copper_b_4"] = { ["building"] = "vik_copper_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_copper_b_5"] = { ["building"] = "vik_copper_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_1"] = { ["building"] = "vik_farm_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_2"] = { ["building"] = "vik_farm_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_3"] = { ["building"] = "vik_farm_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_4"] = { ["building"] = "vik_farm_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_5"] = { ["building"] = "vik_farm_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_b_4"] = { ["building"] = "vik_farm_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_b_5"] = { ["building"] = "vik_farm_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_fishing_1"] = { ["building"] = "vik_fishing_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_fishing_2"] = { ["building"] = "vik_fishing_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_fishing_3"] = { ["building"] = "vik_fishing_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_fishing_4"] = { ["building"] = "vik_fishing_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_fishing_5"] = { ["building"] = "vik_fishing_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_fishing_b_4"] = { ["building"] = "vik_fishing_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_fishing_b_5"] = { ["building"] = "vik_fishing_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_1"] = { ["building"] = "vik_gold_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_2"] = { ["building"] = "vik_gold_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_3"] = { ["building"] = "vik_gold_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_4"] = { ["building"] = "vik_gold_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_5"] = { ["building"] = "vik_gold_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_b_4"] = { ["building"] = "vik_gold_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_b_5"] = { ["building"] = "vik_gold_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_1"] = { ["building"] = "vik_hunting_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_2"] = { ["building"] = "vik_hunting_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_3"] = { ["building"] = "vik_hunting_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_4"] = { ["building"] = "vik_hunting_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_5"] = { ["building"] = "vik_hunting_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_b_4"] = { ["building"] = "vik_hunting_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_b_5"] = { ["building"] = "vik_hunting_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_iron_1"] = { ["building"] = "vik_iron_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_iron_2"] = { ["building"] = "vik_iron_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_iron_3"] = { ["building"] = "vik_iron_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_iron_4"] = { ["building"] = "vik_iron_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_iron_5"] = { ["building"] = "vik_iron_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_iron_b_4"] = { ["building"] = "vik_iron_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_iron_b_5"] = { ["building"] = "vik_iron_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_lead_1"] = { ["building"] = "vik_lead_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_lead_2"] = { ["building"] = "vik_lead_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_lead_3"] = { ["building"] = "vik_lead_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_lead_4"] = { ["building"] = "vik_lead_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_lead_5"] = { ["building"] = "vik_lead_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_lead_b_4"] = { ["building"] = "vik_lead_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_lead_b_5"] = { ["building"] = "vik_lead_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_1"] = { ["building"] = "vik_orchard_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_2"] = { ["building"] = "vik_orchard_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_3"] = { ["building"] = "vik_orchard_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_4"] = { ["building"] = "vik_orchard_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_5"] = { ["building"] = "vik_orchard_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_b_4"] = { ["building"] = "vik_orchard_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_b_5"] = { ["building"] = "vik_orchard_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_1"] = { ["building"] = "vik_pasture_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_2"] = { ["building"] = "vik_pasture_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_3"] = { ["building"] = "vik_pasture_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_4"] = { ["building"] = "vik_pasture_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_5"] = { ["building"] = "vik_pasture_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_b_4"] = { ["building"] = "vik_pasture_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_b_5"] = { ["building"] = "vik_pasture_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pottery_1"] = { ["building"] = "vik_pottery_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pottery_2"] = { ["building"] = "vik_pottery_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pottery_3"] = { ["building"] = "vik_pottery_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pottery_4"] = { ["building"] = "vik_pottery_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pottery_5"] = { ["building"] = "vik_pottery_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pottery_b_4"] = { ["building"] = "vik_pottery_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pottery_b_5"] = { ["building"] = "vik_pottery_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_salt_1"] = { ["building"] = "vik_salt_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_salt_2"] = { ["building"] = "vik_salt_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_salt_3"] = { ["building"] = "vik_salt_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_salt_4"] = { ["building"] = "vik_salt_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_salt_5"] = { ["building"] = "vik_salt_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_salt_b_4"] = { ["building"] = "vik_salt_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_salt_b_5"] = { ["building"] = "vik_salt_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_1"] = { ["building"] = "vik_silver_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_2"] = { ["building"] = "vik_silver_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_3"] = { ["building"] = "vik_silver_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_4"] = { ["building"] = "vik_silver_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_5"] = { ["building"] = "vik_silver_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_b_4"] = { ["building"] = "vik_silver_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_b_5"] = { ["building"] = "vik_silver_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_tin_1"] = { ["building"] = "vik_tin_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_tin_2"] = { ["building"] = "vik_tin_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_tin_3"] = { ["building"] = "vik_tin_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_tin_4"] = { ["building"] = "vik_tin_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_tin_5"] = { ["building"] = "vik_tin_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_tin_b_4"] = { ["building"] = "vik_tin_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_tin_b_5"] = { ["building"] = "vik_tin_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_trade_1"] = { ["building"] = "vik_trade_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_trade_2"] = { ["building"] = "vik_trade_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_trade_3"] = { ["building"] = "vik_trade_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_trade_4"] = { ["building"] = "vik_trade_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_trade_5"] = { ["building"] = "vik_trade_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_trade_b_4"] = { ["building"] = "vik_trade_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_trade_b_5"] = { ["building"] = "vik_trade_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_wood_1"] = { ["building"] = "vik_wood_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_wood_2"] = { ["building"] = "vik_wood_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_wood_3"] = { ["building"] = "vik_wood_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_wood_4"] = { ["building"] = "vik_wood_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_wood_5"] = { ["building"] = "vik_wood_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_wood_b_4"] = { ["building"] = "vik_wood_b_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_wood_b_5"] = { ["building"] = "vik_wood_b_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_b_2"] = { ["building"] = "vik_farm_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_farm_b_3"] = { ["building"] = "vik_farm_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_cloth_b_2"] = { ["building"] = "vik_cloth_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_cloth_b_3"] = { ["building"] = "vik_cloth_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_copper_b_2"] = { ["building"] = "vik_copper_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_copper_b_3"] = { ["building"] = "vik_copper_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_fishing_b_2"] = { ["building"] = "vik_fishing_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_fishing_b_3"] = { ["building"] = "vik_fishing_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_b_2"] = { ["building"] = "vik_gold_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_gold_b_3"] = { ["building"] = "vik_gold_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_b_2"] = { ["building"] = "vik_hunting_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_hunting_b_3"] = { ["building"] = "vik_hunting_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_iron_b_2"] = { ["building"] = "vik_iron_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_iron_b_3"] = { ["building"] = "vik_iron_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_lead_b_2"] = { ["building"] = "vik_lead_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_lead_b_3"] = { ["building"] = "vik_lead_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_b_2"] = { ["building"] = "vik_orchard_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_orchard_b_3"] = { ["building"] = "vik_orchard_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_b_2"] = { ["building"] = "vik_pasture_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pasture_b_3"] = { ["building"] = "vik_pasture_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pottery_b_2"] = { ["building"] = "vik_pottery_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_pottery_b_3"] = { ["building"] = "vik_pottery_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_salt_b_2"] = { ["building"] = "vik_salt_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_salt_b_3"] = { ["building"] = "vik_salt_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_b_2"] = { ["building"] = "vik_silver_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_silver_b_3"] = { ["building"] = "vik_silver_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_tin_b_2"] = { ["building"] = "vik_tin_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_tin_b_3"] = { ["building"] = "vik_tin_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_wood_b_2"] = { ["building"] = "vik_wood_b_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_wood_b_3"] = { ["building"] = "vik_wood_b_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_benedictine_abbey_1"] = { ["building"] = "vik_benedictine_abbey_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_benedictine_abbey_2"] = { ["building"] = "vik_benedictine_abbey_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_benedictine_abbey_3"] = { ["building"] = "vik_benedictine_abbey_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_benedictine_abbey_4"] = { ["building"] = "vik_benedictine_abbey_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_benedictine_abbey_5"] = { ["building"] = "vik_benedictine_abbey_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_celi_de_abbey_1"] = { ["building"] = "vik_celi_de_abbey_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_celi_de_abbey_2"] = { ["building"] = "vik_celi_de_abbey_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_celi_de_abbey_3"] = { ["building"] = "vik_celi_de_abbey_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_celi_de_abbey_4"] = { ["building"] = "vik_celi_de_abbey_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_celi_de_abbey_5"] = { ["building"] = "vik_celi_de_abbey_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_school_ros_1"] = { ["building"] = "vik_school_ros_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_school_ros_2"] = { ["building"] = "vik_school_ros_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_school_ros_3"] = { ["building"] = "vik_school_ros_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_school_ros_4"] = { ["building"] = "vik_school_ros_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_school_ros_5"] = { ["building"] = "vik_school_ros_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_cuthbert_1"] = { ["building"] = "vik_st_cuthbert_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_cuthbert_2"] = { ["building"] = "vik_st_cuthbert_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_cuthbert_3"] = { ["building"] = "vik_st_cuthbert_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_cuthbert_4"] = { ["building"] = "vik_st_cuthbert_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_cuthbert_5"] = { ["building"] = "vik_st_cuthbert_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_dewi_1"] = { ["building"] = "vik_st_dewi_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_dewi_2"] = { ["building"] = "vik_st_dewi_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_dewi_3"] = { ["building"] = "vik_st_dewi_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_dewi_4"] = { ["building"] = "vik_st_dewi_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_dewi_5"] = { ["building"] = "vik_st_dewi_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_edmund_1"] = { ["building"] = "vik_st_edmund_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_edmund_2"] = { ["building"] = "vik_st_edmund_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_edmund_3"] = { ["building"] = "vik_st_edmund_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_edmund_4"] = { ["building"] = "vik_st_edmund_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_edmund_5"] = { ["building"] = "vik_st_edmund_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ringan_1"] = { ["building"] = "vik_st_ringan_1", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ringan_2"] = { ["building"] = "vik_st_ringan_2", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ringan_3"] = { ["building"] = "vik_st_ringan_3", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ringan_4"] = { ["building"] = "vik_st_ringan_4", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ringan_5"] = { ["building"] = "vik_st_ringan_5", ["effect"] = "vik_estates_agricultural", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_achad_bo_1"] = { ["building"] = "vik_achad_bo_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_achad_bo_2"] = { ["building"] = "vik_achad_bo_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_achad_bo_3"] = { ["building"] = "vik_achad_bo_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_achad_bo_4"] = { ["building"] = "vik_achad_bo_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_achad_bo_5"] = { ["building"] = "vik_achad_bo_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_great_hall_1"] = { ["building"] = "vik_great_hall_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_great_hall_2"] = { ["building"] = "vik_great_hall_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_great_hall_3"] = { ["building"] = "vik_great_hall_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_great_hall_4"] = { ["building"] = "vik_great_hall_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_great_hall_5"] = { ["building"] = "vik_great_hall_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_grianan_ailech_1"] = { ["building"] = "vik_grianan_ailech_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_grianan_ailech_2"] = { ["building"] = "vik_grianan_ailech_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_grianan_ailech_3"] = { ["building"] = "vik_grianan_ailech_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_grianan_ailech_4"] = { ["building"] = "vik_grianan_ailech_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_grianan_ailech_5"] = { ["building"] = "vik_grianan_ailech_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_longphort_1"] = { ["building"] = "vik_longphort_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_longphort_2"] = { ["building"] = "vik_longphort_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_longphort_3"] = { ["building"] = "vik_longphort_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_longphort_4"] = { ["building"] = "vik_longphort_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_longphort_5"] = { ["building"] = "vik_longphort_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_market_1"] = { ["building"] = "vik_market_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_market_2"] = { ["building"] = "vik_market_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_market_3"] = { ["building"] = "vik_market_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_market_4"] = { ["building"] = "vik_market_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_market_5"] = { ["building"] = "vik_market_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_monastery_1"] = { ["building"] = "vik_monastery_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_monastery_2"] = { ["building"] = "vik_monastery_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_monastery_3"] = { ["building"] = "vik_monastery_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_monastery_4"] = { ["building"] = "vik_monastery_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_monastery_5"] = { ["building"] = "vik_monastery_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_mountain_hall_1"] = { ["building"] = "vik_mountain_hall_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_mountain_hall_2"] = { ["building"] = "vik_mountain_hall_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_mountain_hall_3"] = { ["building"] = "vik_mountain_hall_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_mountain_hall_4"] = { ["building"] = "vik_mountain_hall_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_mountain_hall_5"] = { ["building"] = "vik_mountain_hall_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_offas_hall_1"] = { ["building"] = "vik_offas_hall_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_offas_hall_2"] = { ["building"] = "vik_offas_hall_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_offas_hall_3"] = { ["building"] = "vik_offas_hall_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_offas_hall_4"] = { ["building"] = "vik_offas_hall_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_offas_hall_5"] = { ["building"] = "vik_offas_hall_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_rock_caisil_1"] = { ["building"] = "vik_rock_caisil_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_rock_caisil_2"] = { ["building"] = "vik_rock_caisil_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_rock_caisil_3"] = { ["building"] = "vik_rock_caisil_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_rock_caisil_4"] = { ["building"] = "vik_rock_caisil_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_rock_caisil_5"] = { ["building"] = "vik_rock_caisil_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ciaran_1"] = { ["building"] = "vik_st_ciaran_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ciaran_2"] = { ["building"] = "vik_st_ciaran_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ciaran_3"] = { ["building"] = "vik_st_ciaran_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ciaran_4"] = { ["building"] = "vik_st_ciaran_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_ciaran_5"] = { ["building"] = "vik_st_ciaran_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_columbe_1"] = { ["building"] = "vik_st_columbe_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_columbe_2"] = { ["building"] = "vik_st_columbe_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_columbe_3"] = { ["building"] = "vik_st_columbe_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_columbe_4"] = { ["building"] = "vik_st_columbe_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_columbe_5"] = { ["building"] = "vik_st_columbe_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_patraic_1"] = { ["building"] = "vik_st_patraic_1", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_patraic_2"] = { ["building"] = "vik_st_patraic_2", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_patraic_3"] = { ["building"] = "vik_st_patraic_3", ["effect"] = "vik_estates_estate_building", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_patraic_4"] = { ["building"] = "vik_st_patraic_4", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 },
	["vik_st_patraic_5"] = { ["building"] = "vik_st_patraic_5", ["effect"] = "vik_estates_religious", ["effect_scope"] = "building_to_building_own", ["value"] = 1, ["value_damaged"] = 1, ["value_ruined"] = 0 }
} --:map<string, {building: string, effect: string, effect_scope: string, value: number, value_damaged: number, value_ruined: number}>

for building, row in pairs(ESTATES_EFFECTS) do
	local effect = string.gsub(row.effect, "estates", "estate")
    et:add_estate_to_building(building, effect)
end

local start_pos_estates = {
	["vik_reg_oxnaforda"] = {"vik_estate_agricultural","2147363335"},
	["vik_reg_licetfelda"] = {"vik_estate_agricultural","2147363186"},
	["vik_reg_staefford"] = {"vik_estate_agricultural","2147363186"},
	["vik_reg_tamworthige"] = {"vik_estate_estate_building","2147363186"},
	["vik_reg_hripum"] = {"vik_estate_agricultural","2147366761"},
	["vik_reg_alclyt"] = {"vik_estate_agricultural","2147366870"},
	["vik_reg_cetretha"] = {"vik_estate_estate_building","2147366870"},
	["vik_reg_dunholm"] = {"vik_estate_agricultural","2147366741"},
	["vik_reg_mameceaster"] = {"vik_estate_estate_building","2147366934"},
	["vik_reg_celmeresfort"] = {"vik_estate_agricultural","2147366822"},
	["vik_reg_lunden"] = {"vik_estate_estate_building","2147366822"},
	["vik_reg_sancte_albanes"] = {"vik_estate_agricultural","2147366822"},
	["vik_reg_tilaburg"] = {"vik_estate_agricultural","2147366822"},
	["vik_reg_rendlesham"] = {"vik_estate_estate_building","2147366738"},
	["vik_reg_wigingamere"] = {"vik_estate_agricultural","2147366862"},
	["vik_reg_casteltoun"] = {"vik_estate_estate_building","2147366232"},
	["vik_reg_inis_patraic"] = {"vik_estate_agricultural","2147366232"},
	["vik_reg_aethelingaeg"] = {"vik_estate_estate_building","2147363123"},
	["vik_reg_glastingburi"] = {"vik_estate_agricultural","2147363123"},
	["vik_reg_waecet"] = {"vik_estate_agricultural","2147363123"},
	["vik_reg_sconnin"] = {"vik_estate_agricultural","2147364675"},
	["vik_reg_axanbrycg"] = {"vik_estate_agricultural","2147363108"},
	["vik_reg_bathanceaster"] = {"vik_estate_agricultural","2147363108"},
	["vik_reg_ethandun"] = {"vik_estate_agricultural","2147363108"},
	["vik_reg_brideport"] = {"vik_estate_agricultural","2147363513"},
	["vik_reg_sceaftesburg"] = {"vik_estate_agricultural","2147363513"},
	["vik_reg_scireburnan"] = {"vik_estate_agricultural","2147363513"},
	["vik_reg_werham"] = {"vik_estate_estate_building","2147363513"},
	["vik_reg_doreceaster"] = {"vik_estate_estate_building","2147363612"},
	["vik_reg_ebbesham"] = {"vik_estate_agricultural","2147363490"},
	["vik_reg_guldeford"] = {"vik_estate_agricultural","2147363490"},
	["vik_reg_ceaster"] = {"vik_estate_estate_building","2147363475"},
	["vik_reg_stoc"] = {"vik_estate_agricultural","2147363475"},
	["vik_reg_waerincwicum"] = {"vik_estate_estate_building","2147363481"},
	["vik_reg_brug"] = {"vik_estate_agricultural","2147363540"},
	["vik_reg_scrobbesburg"] = {"vik_estate_agricultural","2147363540"},
	["vik_reg_alt_clut"] = {"vik_estate_agricultural","2147364076"},
	["vik_reg_cenn_rigmonid"] = {"vik_estate_agricultural","2147364466"},
	["vik_reg_scoan"] = {"vik_estate_estate_building","2147364466"},
	["vik_reg_dear"] = {"vik_estate_agricultural","2147364787"},
	["vik_reg_rinnin"] = {"vik_estate_agricultural","2147364787"},
	["vik_reg_ros_cuissine"] = {"vik_estate_agricultural","2147364787"},
	["vik_reg_maeldune"] = {"vik_estate_agricultural","2147366794"},
	["vik_reg_domuc"] = {"vik_estate_agricultural","2147366741"},
	["vik_reg_doneceaster"] = {"vik_estate_agricultural","2147367004"},
	["vik_reg_dun_beccan"] = {"vik_estate_agricultural","2147365995"},
	["vik_reg_ioua"] = {"vik_estate_estate_building","2147366152"},
	["vik_reg_na_seciri"] = {"vik_estate_agricultural","2147366168"}
}--:map<string, {string, string}>

for region_name, estate_info in pairs(start_pos_estates) do
	et:register_startpos_estate(region_name, estate_info[2], estate_info[1])
end